
const DATA = window.DEMAND_DATA || [];
const METRICS = window.MODEL_METRICS || {};
let currentData = [...DATA];
let mlResults=null;
const mlCharts={};
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const fmt=(n,d=0)=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:d});
const avg=a=>a.length?a.reduce((x,y)=>x+Number(y||0),0)/a.length:0;
const sum=a=>a.reduce((x,y)=>x+Number(y||0),0);
const unique=(key)=>[...new Set(currentData.map(r=>r[key]).filter(v=>v!==null&&v!==''))];
function toast(msg){const t=$("#toast");if(!t)return;t.textContent=msg;t.style.display="block";setTimeout(()=>t.style.display="none",2500)}
function nav(){const p=location.pathname.split("/").pop()||"index.html"; $$(".nav a").forEach(a=>a.classList.toggle("active",a.getAttribute("href")===p));}
function setupMenu(){const m=$("#mobileMenu"),s=$(".sidebar");if(m)m.onclick=()=>s.classList.toggle("open")}
function common(){nav();setupMenu(); const y=$("#year");if(y)y.textContent=new Date().getFullYear();}
function chart(id,type,data,labels,label,opts={}){const el=document.getElementById(id);if(!el)return;new Chart(el,{type,data:{labels,datasets:[{label,data,borderWidth:2,tension:.35,fill:type==="line",backgroundColor:type==="bar"?"rgba(85,214,190,.62)":"rgba(85,214,190,.18)",borderColor:"#55d6be",pointBackgroundColor:"#6ea8fe"}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:"#9db0c8",font:{size:11}}}},scales:type==="pie"?{}:{x:{ticks:{color:"#7188a3"},grid:{color:"rgba(255,255,255,.05)"}},y:{ticks:{color:"#7188a3"},grid:{color:"rgba(255,255,255,.05)"},beginAtZero:true}},...opts}})}
function kpi(id,v){const e=document.getElementById(id);if(e)e.textContent=v}
function renderDashboard(){
 const years=unique("Year"), products=unique("Product"), demands=currentData.map(r=>r.Demand_Units);
 kpi("records",fmt(currentData.length));kpi("products",fmt(products.length));kpi("avgDemand",fmt(avg(demands),1));kpi("avgPrice",fmt(avg(currentData.map(r=>r.Price)),0));kpi("totalDemand",fmt(sum(demands)));kpi("missing",fmt(currentData.reduce((n,r)=>n+Object.values(r).filter(v=>v===null||v==="").length,0)));
 const byMonth={};currentData.forEach(r=>{const k=`${r.Year}-${String(r.Month).padStart(2,"0")}`;byMonth[k]=(byMonth[k]||0)+Number(r.Demand_Units||0)});
 const ks=Object.keys(byMonth).sort();chart("trendChart","line",ks.map(k=>byMonth[k]),ks.map(k=>k.slice(0,7)),"Demand units");
 const byProduct={};currentData.forEach(r=>byProduct[r.Product]=(byProduct[r.Product]||0)+Number(r.Demand_Units||0));
 const pk=Object.keys(byProduct).sort((a,b)=>byProduct[b]-byProduct[a]);chart("productChart","bar",pk.map(k=>byProduct[k]),pk,"Demand units");
 const season={};currentData.forEach(r=>season[r.Season]=(season[r.Season]||0)+Number(r.Demand_Units||0));
 const sk=Object.keys(season);chart("seasonChart","bar",sk.map(k=>season[k]),sk,"Demand units");
 const promo={Promotion:[],NoPromotion:[]};currentData.forEach(r=>(Number(r.Promotion)?promo.Promotion:promo.NoPromotion).push(Number(r.Demand_Units||0)));
 chart("promoChart","bar",[avg(promo.Promotion),avg(promo.NoPromotion)],['Promotion','No promotion'],"Average demand");
 const productLeader=Object.entries(byProduct).sort((a,b)=>b[1]-a[1])[0];
 const monthLeader=Object.entries(byMonth).sort((a,b)=>b[1]-a[1])[0];
 const promoLift=(avg(promo.Promotion)-avg(promo.NoPromotion))/Math.max(avg(promo.NoPromotion),1)*100;
 const priceSensitivity=currentData.reduce((acc,r)=>acc+Math.abs((Number(r.Demand_Units||0)/(Number(r.Price)||1))),0)/Math.max(currentData.length,1);
 const insightGrid=$("#insightGrid");
 if(insightGrid){insightGrid.innerHTML=[
  `<div class="insight-card"><span class="insight-label">Top product</span><strong>${productLeader?.[0] || '—'}</strong><small>${fmt(productLeader?.[1] || 0)} units</small></div>`,
  `<div class="insight-card"><span class="insight-label">Peak month</span><strong>${monthLeader?.[0]?.slice(5) || '—'}</strong><small>${fmt(monthLeader?.[1] || 0)} units</small></div>`,
  `<div class="insight-card"><span class="insight-label">Promo lift</span><strong>${promoLift>=0?'+':''}${promoLift.toFixed(1)}%</strong><small>vs non-promoted demand</small></div>`,
  `<div class="insight-card"><span class="insight-label">Demand signal</span><strong>${priceSensitivity.toFixed(2)}</strong><small>units per price unit</small></div>`
 ].join("");}
 const f=$("#featureList");if(f)f.innerHTML=["Year","Month","Product","Price","Discount_Percent","Advertising_Spend","Previous_Sales_Units","Season","Holiday","Competitor_Price","Stock_Available","Promotion","Demand_Units"].map((x,i)=>`<div class="feature"><div class="num">${String(i+1).padStart(2,"0")}</div><div><b>${x}</b><span>${x==="Demand_Units"?"Target variable":"Predictor / input feature"}</span></div></div>`).join("");
}
function renderDataset(){
 const q=$("#search"), prod=$("#productFilter"), season=$("#seasonFilter"), body=$("#dataBody"), count=$("#tableCount");
 if(prod)prod.innerHTML='<option value="">All products</option>'+unique("Product").map(x=>`<option>${x}</option>`).join("");
 if(season)season.innerHTML='<option value="">All seasons</option>'+unique("Season").map(x=>`<option>${x}</option>`).join("");
 function draw(){
   const query=(q?.value||"").toLowerCase(), pf=prod?.value||"", sf=season?.value||"";
   const filtered=currentData.filter(r=>(!pf||r.Product===pf)&&(!sf||r.Season===sf)&&Object.values(r).join(" ").toLowerCase().includes(query));
   if(count)count.textContent=`${fmt(filtered.length)} records`;
   if(body)body.innerHTML=filtered.slice(0,200).map((r,i)=>`<tr><td>${i+1}</td>${Object.keys(DATA[0]).map(k=>`<td>${r[k]===null?'<span class="pill red">Missing</span>':r[k]}</td>`).join("")}</tr>`).join("");
 }
 [q,prod,season].forEach(e=>e?.addEventListener("input",draw));draw();
}
function renderCorrelationHeatmap(){
 const host=$("#correlationHeatmap");
 if(!host)return;
 const keys=[
  ["Price","Price"],["Discount %","Discount_Percent"],["Advertising Spend","Advertising_Spend"],
  ["Previous Sales","Previous_Sales_Units"],["Competitor Price","Competitor_Price"],["Stock Available","Stock_Available"],["Demand Units","Demand_Units"]
 ];
 const pearson=(a,b)=>{
  const pairs=[];
  for(let i=0;i<Math.min(a.length,b.length);i++){const x=Number(a[i]),y=Number(b[i]);if(Number.isFinite(x)&&Number.isFinite(y))pairs.push([x,y]);}
  if(pairs.length<2)return 0;
  const ax=avg(pairs.map(p=>p[0])),by=avg(pairs.map(p=>p[1]));
  let num=0,dx=0,dy=0;
  pairs.forEach(([x,y])=>{const vx=x-ax,vy=y-by;num+=vx*vy;dx+=vx*vx;dy+=vy*vy});
  return dx&&dy?num/Math.sqrt(dx*dy):0;
 };
 const value=(key)=>currentData.map(r=>r[key]);
 const corr=(a,b)=>pearson(value(a),value(b));
 const color=(v)=>{const x=Math.max(-1,Math.min(1,v));if(x>=0){const r=Math.round(255-(255-163)*x),g=Math.round(255-(255-63)*x),b=Math.round(255-(255-75)*x);return `rgb(${r},${g},${b})`}const t=-x;const r=Math.round(255-(255-53)*t),g=Math.round(255-(255-95)*t),b=Math.round(255-(255-168)*t);return `rgb(${r},${g},${b})`};
 const textColor=(v)=>Math.abs(v)>.58?'#ffffff':'#142033';
 let html='<div class="hm-cell hm-head">Variable</div>'+keys.map(k=>`<div class="hm-cell hm-head">${k[0]}</div>`).join('');
 keys.forEach(([label,key])=>{html+=`<div class="hm-cell hm-head hm-label">${label}</div>`;keys.forEach(([,other])=>{const v=corr(key,other);html+=`<div class="hm-cell hm-value" style="background:${color(v)};color:${textColor(v)}" title="${label} vs ${keys.find(k=>k[1]===other)[0]}: ${v.toFixed(3)}">${v.toFixed(2)}</div>`})});
 host.innerHTML=html;
}

function renderAnalytics(){
 renderCorrelationHeatmap();
 const products=[...new Set(currentData.map(r=>r.Product).filter(v=>v!==null&&v!==undefined&&v!=="").map(String))].sort((a,b)=>a.localeCompare(b));
 function productScatter(canvasId,filterId,xKey,xLabel,tooltipLabel,color){
   const points=currentData.map(r=>({x:Number(r[xKey]),y:Number(r.Demand_Units),product:String(r.Product??"Unknown product")})).filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y));
   const filter=$("#"+filterId);if(!filter)return;
   filter.replaceChildren(new Option("All Products",""),...products.map(product=>new Option(product,product)));
   const canvas=$("#"+canvasId);if(!canvas)return;
  const chartInstance=new Chart(canvas,{type:"scatter",data:{datasets:[{label:xLabel+" vs demand",data:points,backgroundColor:color}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{backgroundColor:"#0d1a2b",titleColor:"#eef5ff",bodyColor:"#dce8f8",borderColor:"#355273",borderWidth:1,callbacks:{title(items){return "Product: "+items[0].raw.product},label(context){const point=context.raw;return [tooltipLabel+": ₹"+fmt(point.x,2),"Demand: "+fmt(point.y)+" units"]}}}},scales:{x:{title:{display:true,text:xLabel,color:"#9db0c8"},ticks:{color:"#7188a3"},grid:{color:"rgba(255,255,255,.05)"}},y:{title:{display:true,text:"Demand units",color:"#9db0c8"},ticks:{color:"#7188a3"},grid:{color:"rgba(255,255,255,.05)"}}}}});
   filter.addEventListener("change",()=>{const selected=filter.value;chartInstance.data.datasets[0].data=selected?points.filter(point=>point.product===selected):points;chartInstance.update();});
 }
 productScatter("priceDemand","priceProductFilter","Price","Price","Price","rgba(110,168,254,.65)");
 productScatter("adDemand","adProductFilter","Advertising_Spend","Advertising spend","Advertising Spend","rgba(85,214,190,.65)");
 const h={Holiday:[],Regular:[]};currentData.forEach(r=>(Number(r.Holiday)?h.Holiday:h.Regular).push(Number(r.Demand_Units||0)));chart("holidayChart","bar",[avg(h.Holiday),avg(h.Regular)],["Holiday","Regular"],"Average demand");
 const stock={Low:[],Medium:[],High:[]};currentData.forEach(r=>{const n=Number(r.Stock_Available);stock[n<300?"Low":n<650?"Medium":"High"].push(Number(r.Demand_Units||0))});chart("stockChart","bar",Object.values(stock).map(avg),Object.keys(stock),"Average demand");
}
async function renderModels(){
 const api="http://127.0.0.1:8000";
 const setText=(id,value)=>{const element=$("#"+id);if(element)element.textContent=value};
 const number=(value,d=2)=>Number(value||0).toFixed(d);
 const showError=message=>{const error=$("#mlError");if(error){error.textContent=message;error.style.display="block"}setText("modelsStatus","● API Offline");$("#modelsStatus")?.classList.add("offline");setText("healthApi","● Offline")};
 const downloadText=(text,name,type="text/csv")=>download(new Blob([text],{type}),name);
 const csv=(rows)=>rows.map(row=>row.map(value=>`"${String(value??"").replaceAll('"','""')}"`).join(",")).join("\n");
 const values=()=>Object.fromEntries(new FormData($("#mlLabForm")).entries());
 const numericKeys=["Year","Month","Price","Discount_Percent","Advertising_Spend","Previous_Sales_Units","Holiday","Competitor_Price","Stock_Available","Promotion"];
 const destroyChart=id=>{if(mlCharts[id]){mlCharts[id].destroy();delete mlCharts[id]}};
 const chartBase={responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:"#9db0c8",font:{size:11}}}},scales:{x:{ticks:{color:"#7188a3"},grid:{color:"rgba(255,255,255,.05)"}},y:{ticks:{color:"#7188a3"},grid:{color:"rgba(255,255,255,.05)"}}}};
 const renderPerformance=()=>{const metric=$("#performanceMetric")?.value||"mae";destroyChart("performance");const factor=metric==="r2"?100:1;const labels=metric==="r2"?"R² Score (%)":metric.toUpperCase();mlCharts.performance=new Chart($("#modelChart"),{type:"bar",data:{labels:["Ridge Regression","Lasso Regression"],datasets:[{label:labels,data:[mlResults.models.ridge.metrics[metric]*factor,mlResults.models.lasso.metrics[metric]*factor],backgroundColor:["rgba(110,168,254,.72)","rgba(85,214,190,.72)"],borderColor:["#6ea8fe","#55d6be"],borderWidth:1}]},options:{...chartBase,plugins:{...chartBase.plugins,tooltip:{callbacks:{label:context=>`${labels}: ${number(context.raw,metric==="r2"?2:2)}`}}}}})};
 const renderActual=()=>{const model=$("#actualModel")?.value||"ridge", rows=mlResults.models[model].actual_vs_predicted;destroyChart("actual");const max=Math.max(...rows.flatMap(row=>[row.actual,row.predicted]));mlCharts.actual=new Chart($("#actualPredictedChart"),{type:"scatter",data:{datasets:[{label:"Predictions",data:rows.map(row=>({x:row.actual,y:row.predicted})),backgroundColor:"rgba(110,168,254,.7)"},{label:"Perfect Prediction",data:[{x:0,y:0},{x:max,y:max}],type:"line",borderColor:"#f5b94c",borderDash:[6,5],pointRadius:0}]},options:{...chartBase,scales:{x:{...chartBase.scales.x,title:{display:true,text:"Actual Demand (Units)",color:"#9db0c8"}},y:{...chartBase.scales.y,title:{display:true,text:"Predicted Demand (Units)",color:"#9db0c8"}}},plugins:{...chartBase.plugins,tooltip:{callbacks:{label:context=>{if(context.datasetIndex!==0)return "Perfect Prediction";const error=context.raw.y-context.raw.x;return [`Actual Demand: ${number(context.raw.x,0)} units`,`Predicted Demand: ${number(context.raw.y,0)} units`,`Error: ${number(error,0)} units`,`Absolute Error: ${number(Math.abs(error),0)} units`]}}}}}})};
 const renderResidual=()=>{const model=$("#residualModel")?.value||"ridge", rows=mlResults.models[model].residuals;destroyChart("residual");const min=Math.min(...rows.map(row=>row.predicted));const max=Math.max(...rows.map(row=>row.predicted));mlCharts.residual=new Chart($("#residualChart"),{type:"scatter",data:{datasets:[{label:"Residuals",data:rows.map(row=>({x:row.predicted,y:row.residual})),backgroundColor:"rgba(85,214,190,.7)"},{label:"Zero residual",data:[{x:min,y:0},{x:max,y:0}],type:"line",borderColor:"#f5b94c",borderDash:[6,5],pointRadius:0}]},options:{...chartBase,scales:{x:{...chartBase.scales.x,title:{display:true,text:"Predicted Demand",color:"#9db0c8"}},y:{...chartBase.scales.y,title:{display:true,text:"Residual",color:"#9db0c8"}}},plugins:{...chartBase.plugins,tooltip:{callbacks:{label:context=>`Residual: ${number(context.raw.y,2)} units`}}}}})};
 const renderErrors=()=>{const model=$("#errorModel")?.value||"ridge", data=mlResults.models[model], errors=data.errors;destroyChart("errors");const min=Math.floor(Math.min(...errors)/10)*10,max=Math.ceil(Math.max(...errors)/10)*10,bins=Math.max(5,Math.min(12,Math.ceil((max-min)/10)||5)),step=(max-min||1)/bins,counts=Array(bins).fill(0);errors.forEach(error=>counts[Math.min(bins-1,Math.max(0,Math.floor((error-min)/step)))]++);mlCharts.errors=new Chart($("#errorChart"),{type:"bar",data:{labels:counts.map((_,i)=>`${number(min+i*step,0)} to ${number(min+(i+1)*step,0)}`),datasets:[{label:"Error frequency",data:counts,backgroundColor:"rgba(245,185,76,.65)",borderColor:"#f5b94c",borderWidth:1}]},options:{...chartBase,plugins:{...chartBase.plugins,legend:{display:false}}}});setText("meanError",number(data.mean_error));setText("medianError",number(data.median_error));setText("maxError",number(data.max_error));setText("minError",number(data.min_error))};
 const renderCoefficients=()=>{const model=$("#coefficientModel")?.value||"ridge", rows=[...mlResults.models[model].coefficients].sort((a,b)=>Math.abs(b.coefficient)-Math.abs(a.coefficient)).slice(0,15).reverse();destroyChart("coefficients");mlCharts.coefficients=new Chart($("#coefficientChart"),{type:"bar",data:{labels:rows.map(row=>row.feature.replace(/^num__|^cat__/,"")),datasets:[{label:"Coefficient",data:rows.map(row=>row.coefficient),backgroundColor:rows.map(row=>row.coefficient>=0?"rgba(85,214,190,.72)":"rgba(255,107,122,.72)"),borderColor:rows.map(row=>row.coefficient>=0?"#55d6be":"#ff6b7a"),borderWidth:1}]},options:{indexAxis:"y",...chartBase,plugins:{...chartBase.plugins,tooltip:{callbacks:{label:context=>`Coefficient: ${context.raw>=0?"+":""}${number(context.raw,3)} | Direction: ${context.raw>=0?"Positive":"Negative"}`}}}}})};
 const renderLists=()=>{const data=mlResults.models.lasso, selected=data.selected_input_features||[], removed=data.zero_input_features||[];setText("totalCoefficients",mlResults.dataset.input_features);setText("selectedCoefficients",selected.length);setText("zeroCoefficients",removed.length);const list=(id,rows)=>{const element=$("#"+id);if(element)element.innerHTML=rows.length?rows.map(row=>`<li>${row}</li>`).join(""):"<li>None</li>"};list("selectedFeatureList",selected);list("removedFeatureList",removed)};
 const renderResults=()=>{const ridge=mlResults.models.ridge,lasso=mlResults.models.lasso,dataset=mlResults.dataset;[["ridgeR2",`${number(ridge.metrics.r2*100,2)}%`],["ridgeRMSE",number(ridge.metrics.rmse)],["ridgeMAE",number(ridge.metrics.mae)],["ridgeFeatures",ridge.features_used],["ridgeAlpha",ridge.alpha],["lassoR2",`${number(lasso.metrics.r2*100,2)}%`],["lassoRMSE",number(lasso.metrics.rmse)],["lassoMAE",number(lasso.metrics.mae)],["lassoFeatures",(lasso.selected_input_features||[]).length],["lassoAlpha",lasso.alpha],["compareRidgeMAE",number(ridge.metrics.mae)],["compareLassoMAE",number(lasso.metrics.mae)],["compareRidgeMSE",number(ridge.metrics.mse)],["compareLassoMSE",number(lasso.metrics.mse)],["compareRidgeRMSE",number(ridge.metrics.rmse)],["compareLassoRMSE",number(lasso.metrics.rmse)],["compareRidgeR2",`${number(ridge.metrics.r2*100,2)}%`],["compareLassoR2",`${number(lasso.metrics.r2*100,2)}%`],["configDataset",dataset.total_records],["configFeatures",dataset.input_features],["configTarget",dataset.target],["configTrain",dataset.training_records],["configTest",dataset.testing_records],["configSplit",dataset.split_ratio],["lastEvaluation",`Last Evaluation: ${new Date(mlResults.timestamp).toLocaleString()}`],["healthEvaluation",new Date(mlResults.timestamp).toLocaleString()]].forEach(([id,value])=>setText(id,value));$("#ridgeAlphaInput").value=ridge.alpha;$("#lassoAlphaInput").value=lasso.alpha;$("#lassoIterationsInput").value=lasso.max_iterations||10000;setText("modelsStatus","● Models Ready");setText("datasetStatus",`Dataset Connected · ${dataset.total_records} records`);setText("evaluationState","Live evaluation loaded");setText("healthApi","● Online");renderLists();renderPerformance();renderActual();renderResidual();renderErrors();renderCoefficients()};
 const load=async endpoint=>{try{const response=await fetch(`${api}${endpoint}`);if(!response.ok)throw new Error(`Request failed (${response.status})`);mlResults=await response.json();$("#mlError").style.display="none";renderResults()}catch(error){showError(`Could not load live ML results. Start the FastAPI backend at ${api}. ${error.message}`)}};
 await load("/ml-results");
 ["performanceMetric","actualModel","residualModel","errorModel","coefficientModel"].forEach(id=>$("#"+id)?.addEventListener("change",()=>{if(id==="performanceMetric")renderPerformance();if(id==="actualModel")renderActual();if(id==="residualModel")renderResidual();if(id==="errorModel")renderErrors();if(id==="coefficientModel")renderCoefficients()}));
 $("#refreshResults")?.addEventListener("click",()=>load("/ml-results"));$("#runEvaluation")?.addEventListener("click",()=>load("/ml-results"));$("#exportMLReport")?.addEventListener("click",()=>$("#generateMlPdf")?.click());
 $("#presentationMode")?.addEventListener("click",()=>{$("#mlMain")?.classList.toggle("presentation-mode")});
 $("#retrainModels")?.addEventListener("click",async()=>{const button=$("#retrainModels");button.disabled=true;button.textContent="Retraining...";try{const response=await fetch(`${api}/retrain`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ridge_alpha:Number($("#ridgeAlphaInput").value),lasso_alpha:Number($("#lassoAlphaInput").value),lasso_max_iter:Number($("#lassoIterationsInput").value)})});if(!response.ok)throw new Error("Retraining failed");mlResults=await response.json();renderResults();toast("Models retrained with live results")}catch(error){showError(error.message)}finally{button.disabled=false;button.textContent="Retrain Models"}});
 const historyKey="demandIQPredictionHistory";const readHistory=()=>{try{return JSON.parse(localStorage.getItem(historyKey)||"[]")}catch{return[]}};const renderHistory=()=>{const rows=readHistory(),body=$("#predictionHistory");if(body)body.innerHTML=rows.length?rows.map(row=>`<tr><td>${new Date(row.time).toLocaleString()}</td><td>${row.product}</td><td>${row.model.toUpperCase()}</td><td>${fmt(row.prediction,0)} units</td></tr>`).join(""):"<tr><td colspan=4>No predictions yet.</td></tr>"};renderHistory();
 $("#mlLabForm")?.addEventListener("submit",async event=>{event.preventDefault();const button=event.currentTarget.querySelector("button[type=submit]"),model=$("#labModel").value,payload=values();numericKeys.forEach(key=>payload[key]=Number(payload[key]));button.disabled=true;button.textContent="Predicting...";try{const response=await fetch(`${api}/predict`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model,...payload})});if(!response.ok)throw new Error("Prediction request failed");const result=await response.json(),history=readHistory();history.unshift({time:new Date().toISOString(),product:payload.Product,model,prediction:result.prediction});localStorage.setItem(historyKey,JSON.stringify(history.slice(0,25)));renderHistory();const context=mlResults.models[model];const output=$("#labResult");output.style.display="block";output.innerHTML=`<div class="result-header"><span class="status-badge success">Live model</span><span class="result-type">${model.toUpperCase()} regression</span></div><div class="big">${fmt(result.prediction,0)} units</div><p class="result-meta">R² = ${number(context.metrics.r2*100,2)}% · Input processed successfully.</p>`}catch(error){showError(error.message)}finally{button.disabled=false;button.textContent="Predict Demand"}});
 $("#clearPredictionHistory")?.addEventListener("click",()=>{localStorage.removeItem(historyKey);renderHistory()});$("#exportPredictionHistory")?.addEventListener("click",()=>{const rows=readHistory();downloadText(csv([["Time","Product","Model","Predicted Demand"],...rows.map(row=>[row.time,row.product,row.model,row.prediction])]),"DemandIQ_Prediction_History.csv")});
 $("#exportMetricsCsv")?.addEventListener("click",()=>downloadText(csv([["Metric","Ridge","Lasso"],["MAE",mlResults.models.ridge.metrics.mae,mlResults.models.lasso.metrics.mae],["MSE",mlResults.models.ridge.metrics.mse,mlResults.models.lasso.metrics.mse],["RMSE",mlResults.models.ridge.metrics.rmse,mlResults.models.lasso.metrics.rmse],["R2",mlResults.models.ridge.metrics.r2,mlResults.models.lasso.metrics.r2]]),"DemandIQ_ML_Metrics.csv"));$("#exportCoefficientsCsv")?.addEventListener("click",()=>downloadText(csv([["Model","Feature","Coefficient"],...["ridge","lasso"].flatMap(model=>mlResults.models[model].coefficients.map(row=>[model,row.feature,row.coefficient]))]),"DemandIQ_Coefficients.csv"));$("#exportResultsXlsx")?.addEventListener("click",()=>{const workbook=XLSX.utils.book_new();XLSX.utils.book_append_sheet(workbook,XLSX.utils.aoa_to_sheet([["Metric","Ridge","Lasso"],["MAE",mlResults.models.ridge.metrics.mae,mlResults.models.lasso.metrics.mae],["MSE",mlResults.models.ridge.metrics.mse,mlResults.models.lasso.metrics.mse],["RMSE",mlResults.models.ridge.metrics.rmse,mlResults.models.lasso.metrics.rmse],["R2",mlResults.models.ridge.metrics.r2,mlResults.models.lasso.metrics.r2]]),"Metrics");XLSX.utils.book_append_sheet(workbook,XLSX.utils.json_to_sheet(mlResults.models.ridge.coefficients),"Ridge Coefficients");XLSX.utils.book_append_sheet(workbook,XLSX.utils.json_to_sheet(mlResults.models.lasso.coefficients),"Lasso Coefficients");XLSX.writeFile(workbook,"DemandIQ_ML_Results.xlsx")});$("#generateMlPdf")?.addEventListener("click",()=>{if(!window.jspdf)return toast("PDF library unavailable");const {jsPDF}=window.jspdf,doc=new jsPDF();doc.setFontSize(18);doc.text("DemandIQ - ML Evaluation Report",15,18);doc.setFontSize(10);doc.text(`Records: ${mlResults.dataset.total_records} | Train: ${mlResults.dataset.training_records} | Test: ${mlResults.dataset.testing_records}`,15,30);doc.text(`Ridge MAE ${number(mlResults.models.ridge.metrics.mae)} | RMSE ${number(mlResults.models.ridge.metrics.rmse)} | R2 ${number(mlResults.models.ridge.metrics.r2*100)}%`,15,40);doc.text(`Lasso MAE ${number(mlResults.models.lasso.metrics.mae)} | RMSE ${number(mlResults.models.lasso.metrics.rmse)} | R2 ${number(mlResults.models.lasso.metrics.r2*100)}%`,15,50);doc.text("Actual model evaluation generated from the FastAPI service.",15,64);let y=76;["actualPredictedChart","residualChart","coefficientChart"].forEach(id=>{const canvas=$("#"+id);if(canvas){doc.addImage(canvas.toDataURL("image/png"),"PNG",15,y,180,70);y+=78;if(y>220){doc.addPage();y=20}}});doc.save("DemandIQ_ML_Report.pdf")});
}
function setupPrediction(){
 const form=$("#predictForm"), out=$("#predictionResult"), model=$("#modelSelect");
 form?.addEventListener("submit",async e=>{e.preventDefault();
  const submitBtn=form.querySelector("button[type='submit']") || form.querySelector("button");
  const obj=Object.fromEntries(new FormData(form).entries());
  ["Year","Month","Price","Discount_Percent","Advertising_Spend","Previous_Sales_Units","Holiday","Competitor_Price","Stock_Available","Promotion"].forEach(k=>obj[k]=Number(obj[k]));
  if(submitBtn){submitBtn.disabled=true;submitBtn.textContent="Predicting...";submitBtn.classList.add("loading");}
  try{const resp=await fetch("http://127.0.0.1:8000/predict",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model:model.value,...obj})});if(!resp.ok)throw 0;const j=await resp.json();out.style.display="block";out.innerHTML=`<div class="result-header"><span class="status-badge success">Live model</span><span class="result-type">${model.value.toUpperCase()} regression</span></div><div class="big">${fmt(j.prediction,0)} units</div><p class="result-meta">Prediction generated by the trained ${model.value.toUpperCase()} regression pipeline.</p>`}
  catch{const base=.45*Number(obj.Previous_Sales_Units)+.25*Number(obj.Stock_Available)+.001*Number(obj.Advertising_Spend)-.001*Number(obj.Price)+2*Number(obj.Discount_Percent)+25*Number(obj.Promotion);out.style.display="block";out.innerHTML=`<div class="result-header"><span class="status-badge warning">Demo fallback</span><span class="result-type">Local estimate</span></div><div class="big">${fmt(Math.max(0,base),0)} units</div><p class="result-meta">Backend not running. Start the FastAPI backend to use the actual trained model.</p>`}
  finally{if(submitBtn){submitBtn.disabled=false;submitBtn.textContent="Predict demand →";submitBtn.classList.remove("loading");}}
 });
}
function exportCSV(){
 const keys=Object.keys(currentData[0]||{});const rows=[keys,...currentData.map(r=>keys.map(k=>r[k]??""))];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");download(new Blob([csv],{type:"text/csv"}),"demand_data.csv");
}
function exportXLSX(){if(!window.XLSX)return toast("Excel library unavailable");const ws=XLSX.utils.json_to_sheet(currentData),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Demand Data");XLSX.writeFile(wb,"DemandIQ_Data.xlsx");}
function exportPDF(){if(!window.jspdf)return toast("PDF library unavailable");const {jsPDF}=window.jspdf,doc=new jsPDF();doc.setFontSize(20);doc.text("DemandIQ — Demand Forecasting Report",15,18);doc.setFontSize(10);doc.text(`Records: ${currentData.length}`,15,30);doc.text(`Average demand: ${avg(currentData.map(r=>r.Demand_Units)).toFixed(2)} units`,15,38);doc.text(`Ridge R²: ${(METRICS.ridge.r2*100).toFixed(2)}%`,15,46);doc.text(`Lasso R²: ${(METRICS.lasso.r2*100).toFixed(2)}%`,15,54);doc.text("Dataset-driven analytics report generated by DemandIQ.",15,66);doc.save("DemandIQ_Report.pdf")}
function download(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function setupExports(){document.querySelectorAll(".export-csv-btn").forEach(btn=>btn.addEventListener("click",exportCSV));document.querySelectorAll(".export-xlsx-btn").forEach(btn=>btn.addEventListener("click",exportXLSX));document.querySelectorAll(".export-pdf-btn").forEach(btn=>btn.addEventListener("click",exportPDF));}
function setupUpload(){document.querySelectorAll(".excel-upload-input").forEach(input=>input.addEventListener("change",e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=ev=>{try{const wb=XLSX.read(ev.target.result,{type:"array"});const ws=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json(ws,{defval:null});if(!rows.length)throw 0;currentData=rows;localStorage.setItem("demandIQData",JSON.stringify(rows));toast(`Loaded ${rows.length} records from Excel`);setTimeout(()=>location.reload(),500)}catch{toast("Could not read this Excel file")}};reader.readAsArrayBuffer(file)}))}
document.addEventListener("DOMContentLoaded",()=>{common();setupExports();setupUpload();const saved=localStorage.getItem("demandIQData");if(saved)try{currentData=JSON.parse(saved)}catch{};const page=document.body.dataset.page;if(page==="dashboard")renderDashboard();if(page==="dataset")renderDataset();if(page==="analytics")renderAnalytics();if(page==="models")renderModels();if(page==="prediction")setupPrediction();if(page==="reports"){kpi("reportRecords",fmt(currentData.length));kpi("reportDemand",fmt(avg(currentData.map(r=>r.Demand_Units)),1));kpi("ridgeReportR2",`${(METRICS.ridge.r2*100).toFixed(1)}%`);kpi("lassoReportR2",`${(METRICS.lasso.r2*100).toFixed(1)}%`);}$("#clearData")?.addEventListener("click",()=>{localStorage.removeItem("demandIQData");location.reload()})});
